export const LOGIN_USER = 'login_user';
export const LOGOUT_USER = 'logout_user';
export const REGISTER_USER = 'register_user';
export const AUTH_USER = 'auth_user';
export const GET_PRODUCTS_BY_SALE = 'get_products_by_sale';
export const GET_PRODUCTS_BY_ARRIVAL = 'get_products_by_arrival';
export const GET_PRODUCTS_BY_BRANDS = 'get_products_by_brand'
export const GET_PRODUCTS_BY_WOODS = 'get_products_by_woods'
export const GET_PRODUCTS_TO_SHOP = 'get_products_to_shop'
export const ADD_PRODUCT = 'add_product' 
export const CLEAR_PRODUCT = 'clear_product'
export const ADD_BRAND = 'add_brand'
export const ADD_WOOD = 'add_wood'
export const CLEAR_PRODUCT_DETAIL = 'clear_product_detail' 
export const GET_PRODUCT_DETAIL = 'get_product_detail'
export const ADD_TO_CART= 'add_to_cart'
export const GET_CART_ITEMS= 'get_cart_items'
export const REMOVE_CART_ITEMS='remove_cart_items'
export const ON_SUCCESS_BUY='on_success_buy'